from tkinter import *

window=Tk()

mainFrame=Frame(window,bg="#1B2631")
mainFrame.pack(expand=True,fill="both")

frame=Frame(mainFrame,bg="#F39C12",height=200,padx=5,pady=5)
label=Label(frame,text="Single Full Screen",padx=10,pady=10,relief="raised")
label.config(font=("Arial","18"))
label.pack(fill="x")
label=Label(frame,text="Single Full Screen",padx=10,pady=10,relief="raised")
label.config(font=("Arial","18"))
label.pack(fill="x")
label=Label(frame,text="Single Full Screen",padx=10,pady=10,relief="raised")
label.config(font=("Arial","18"))
label.pack(fill="x")
label=Label(frame,text="Single Full Screen",padx=10,pady=10,relief="raised")
label.config(font=("Arial","18"))
label.pack(fill="x")
frame.pack(fill="x")


frame2=Frame(mainFrame,bg="#9B59B6",height=200,padx=5,pady=5)
label=Label(frame2,text="Double Column Full 1",padx=10,pady=10,relief="raised")
label.config(font=("Arial","18"))
label.grid(row=0,column=0,sticky="nsew")
label=Label(frame2,text="Double Column Full 2",padx=10,pady=10,relief="raised")
label.config(font=("Arial","18"))
label.grid(row=0,column=1,sticky="nsew")
label=Label(frame2,text="Double Column Full 3",padx=10,pady=10,relief="raised")
label.config(font=("Arial","18"))
label.grid(row=0,column=2,sticky="nsew")
label=Label(frame2,text="Double Column Full 4",padx=10,pady=10,relief="raised")
label.config(font=("Arial","18"))
label.grid(row=0,column=3,sticky="nsew")
frame2.pack(fill="x")
frame2.grid_columnconfigure(0, weight=1)
frame2.grid_columnconfigure(1, weight=1)
frame2.grid_columnconfigure(2, weight=1)
frame2.grid_columnconfigure(3, weight=1)

frame3=Frame(mainFrame,bg="#9B59B6",height=200,padx=5,pady=5)
label=Label(frame3,text="Double Column Full 1",padx=10,pady=10,relief="raised")
label.config(font=("Arial","18"))
label.grid(row=0,column=0,sticky="nsew")
label=Label(frame3,text="Double Column Full 2",padx=10,pady=10,relief="raised")
label.config(font=("Arial","18"))
label.grid(row=0,column=1,sticky="nsew")
label=Label(frame3,text="Double Column Full 3",padx=10,pady=10,relief="raised")
label.config(font=("Arial","18"))
label.grid(row=0,column=2,sticky="nsew")
label=Label(frame3,text="Double Column Full 4",padx=10,pady=10,relief="raised")
label.config(font=("Arial","18"))
label.grid(row=0,column=3,sticky="nsew")
frame3.pack(fill="x")
label=Label(frame3,text="Double Column Full 1",padx=10,pady=10,relief="raised")
label.config(font=("Arial","18"))
label.grid(row=1,column=0,sticky="nsew")
label=Label(frame3,text="Double Column Full 2",padx=10,pady=10,relief="raised")
label.config(font=("Arial","18"))
label.grid(row=1,column=1,sticky="nsew")
label=Label(frame3,text="Double Column Full 3",padx=10,pady=10,relief="raised")
label.config(font=("Arial","18"))
label.grid(row=1,column=2,sticky="nsew")
label=Label(frame3,text="Double Column Full 4",padx=10,pady=10,relief="raised")
label.config(font=("Arial","18"))
label.grid(row=1,column=3,sticky="nsew")
frame3.pack(fill="x")
frame3.grid_columnconfigure(0, weight=1)
frame3.grid_columnconfigure(1, weight=1)
frame3.grid_columnconfigure(2, weight=1)
frame3.grid_columnconfigure(3, weight=1)

window.mainloop()